package exceptionprogm;

public class Exception5 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try
		{
		int a[]= {2,3,4};
		System.out.println(a[3]);
		}
		catch(Exception e)
		{
			System.out.println("Index out of bounds");
	}
	

	}

}
